# Generated by Django 4.0.1 on 2022-04-29 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
